filosofos_wikipedia_a_c = ['Adi Shankara',
                           'Nicola Abbagnano',
                           'Muhammad Abduh',
                           'Peter Abelard',
                           'Abhinavagupta',
                           'Isaac ben Judah Abravanel',
                           'Judah ben Isaac Abravanel',
                           'Marilyn McCord Adams',
                           'Robert Adams',
                           'Joseph Addison',
                           'Adelard of Bath',
                           'Alfred Adler',
                           'Theodor Adorno',
                           'Aenesidemus',
                           'Jamal al-Din al-Afghani',
                           'Rodolphus Agricola',
                           'Agrippa the Sceptic',
                           'Heinrich Cornelius Agrippa',
                           "Pierre d'Ailly",
                           'Kazimierz Ajdukiewicz',
                           'Hans Albert',
                           'Albert of Saxony',
                           'Albertus Magnus',
                           'Joseph Albo',
                           'Alcinous',
                           'Alcmaeon of Croton',
                           'Virgil Aldrich',
                           'Yohanan ben Isaac Alemanno',
                           'Alexander of Aphrodisias',
                           'Alexander of Hales',
                           'Samuel Alexander',
                           'Dante Alighieri',
                           'Antonio Aliotta',
                           'Archibald Alison',
                           'Abd al-Jabiri',
                           'Abdullah al-Qasemi',
                           'William Alston',
                           'Johannes Althusius',
                           'Louis Althusser',
                           'Robert Alyngton',
                           'Bhimrao Ambedkar',
                           'Ambrose',
                           "Abu'l Hasan Muhammad Ibn Yusuf al-'Amiri",
                           'Ammonius Hermiae',
                           'Ammonius Saccas',
                           'André-Marie Ampère',
                           'Anton Wilhelm Amo',
                           'Anaxagoras',
                           'Anaxarchus',
                           'Anaximander',
                           'Anaximenes of Miletus',
                           'Alan Ross Anderson',
                           'John Anderson',
                           'Ando Shoeki',
                           'Andronicus of Rhodes',
                           'Peter Annet',
                           'Anniceris',
                           'G. E. M. Anscombe',
                           'Anselm',
                           'Antiochus of Ascalon',
                           'Antiphon',
                           'Antisthenes',
                           'Karl-Otto Apel',
                           'Apuleius',
                           'Thomas Aquinas',
                           'Isaac ben Moses Arama',
                           'Arcesilaus',
                           'Archytas',
                           'Roberto Ardigò',
                           'Hannah Arendt',
                           'Aristippus of Cyrene',
                           'Aristo of Chios',
                           'Aristotle',
                           'Arius',
                           'Mohammed Arkoun',
                           'Jacobus Arminius',
                           'David Malet Armstrong',
                           'Antoine Arnauld',
                           'Matthew Arnold',
                           'Kenneth Arrow',
                           'Valentin Ferdinandovich Asmus',
                           'Mary Astell',
                           'Athanasius of Alexandria',
                           'Gwenaëlle Aubry',
                           'Augustine of Hippo',
                           'Marcus Aurelius',
                           'Peter Aureol',
                           'Sri Aurobindo',
                           'John Austin',
                           'John Langshaw Austin',
                           'Richard Avenarius',
                           'Averroes',
                           'Avicenna',
                           'Alfred Jules Ayer',
                           'Franz Xaver von Baader',
                           'Charles Babbage',
                           'Gaston Bachelard',
                           'Johann Jakob Bachofen',
                           'Francis Bacon',
                           'Roger Bacon',
                           'Alain Badiou',
                           "Hibat Allah Abu'l-Barakat al-Baghdaadi",
                           'Annette Baier',
                           'Kurt Baier',
                           'Alexander Bain',
                           'Karl Friedrich Bahrdt',
                           'Lynne Rudder Baker',
                           'Mikhail Bakhtin',
                           'Mikhail Bakunin',
                           'Arthur Balfour',
                           'John Balguy',
                           'Domingo Báñez',
                           'Antonio Banfi',
                           'Abraham bar Hiyya Ha-Nasi',
                           'Jonathan Barnes',
                           'Brian Barry',
                           'Karl Barth',
                           'Roland Barthes',
                           'Bartolus de Saxoferrato',
                           'Johann Bernhard Basedow',
                           'Basilides',
                           'Georges Bataille',
                           'Charles Batteux',
                           'Jean Baudrillard',
                           'Bruno Bauer',
                           'David Baumgardt',
                           'Alexander Gottlieb Baumgarten',
                           'Pierre Bayle',
                           'Monroe Beardsley',
                           'James Beattie',
                           'Cesare, Marquis of Beccaria',
                           'Jakob Sigismund Beck',
                           'Vissarion Belinsky',
                           'Robert Bellarmine',
                           'Nuel Belnap',
                           'Gustave Belot',
                           'Friedrich Eduard Beneke',
                           'Walter Benjamin',
                           'Gottfried Benn',
                           'Jonathan Bennett',
                           'Jeremy Bentham',
                           'Richard Bentley',
                           'Nikolai Berdyaev',
                           'Gustav Bergmann',
                           'Henri Bergson',
                           'George Berkeley',
                           'Isaiah Berlin',
                           'Claude Bernard',
                           'Bernard of Chartres',
                           'Bernard of Clairvaux',
                           'Bernard Silvestris',
                           'François Bernier',
                           'Eduard Bernstein',
                           'Ludwig von Bertalanffy',
                           'Bhartrhari',
                           'Gabriel Biel',
                           'Georg Bernhard Bilfinger',
                           'Alfred Binet',
                           'Ludwig Binswanger',
                           'Max Black',
                           'Simon Blackburn',
                           'William Blackstone',
                           'Hugh Blair',
                           'William Blake',
                           'Maurice Blanchot',
                           'Brand Blanshard',
                           'Blasius of Parma',
                           'Ernst Bloch',
                           'Ned Block',
                           'Maurice Blondel',
                           'Charles Blount',
                           'Norberto Bobbio',
                           'Jean Bodin',
                           'Anicius Manlius Severinus Boethius',
                           'Boetius of Dacia',
                           'Alexander Bogdanov',
                           'Jakob Böhme',
                           'David Bohm',
                           'Niels Bohr',
                           'Nicolas Boileau-Despréaux',
                           'Samuel Bold',
                           'Henry St John, 1st Viscount Bolingbroke',
                           'Ludwig Boltzmann',
                           'Bernard Bolzano',
                           'Louis Gabriel Ambroise de Bonald',
                           'Francesco Bonatelli',
                           'Bonaventure',
                           'Dietrich Bonhoeffer',
                           'Charles Bonnet',
                           'George Boole',
                           'Bernard Bosanquet',
                           'Rudjer Boscovich',
                           'Pierre Bourdieu',
                           'Jacques-Bénigne Bossuet',
                           'Christopher Jacob Boström',
                           'Henri de Boulainvilliers',
                           'Emile Boutroux',
                           'Oets Kolk Bouwsma',
                           'Borden Parker Bowne',
                           'Robert Boyle',
                           'F. H. Bradley',
                           'Thomas Bradwardine',
                           'Richard-Bevan Braithwaite',
                           'Richard B. Brandt',
                           'Franz Brentano',
                           'Percy Williams Bridgman',
                           'Edgar S. Brightman',
                           'Jean Anthelme Brillat-Savarin',
                           'Richard Brinkley',
                           'Radulphus Brito',
                           'C. D. Broad',
                           'Thom Brooks',
                           'Luitzen Egbertus Jan Brouwer',
                           'Thomas Brown',
                           'Peter Browne',
                           'Orestes Brownson',
                           'Emil Brunner',
                           'Giordano Bruno',
                           'Leon Brunschvicg',
                           'James Bryce, 1st Viscount Bryce',
                           'Martin Buber',
                           'Justus Buchler',
                           'Ludwig Büchner',
                           'Henry Thomas Buckle',
                           'Malcolm Budd',
                           'Johann Franz Buddeus',
                           'Buddhaghosa',
                           'Claude Buffier',
                           'Georges-Louis Leclerc, Comte de Buffon',
                           'Sergei Nikolaevich Bulgakov',
                           'Edward Bullough',
                           'Rudolf Bultmann',
                           'Jacob Burckhardt',
                           'Tyler Burge',
                           'Jean Buridan',
                           'Edmund Burke',
                           'Walter Burley',
                           'Myles Frederic Burnyeat',
                           'Richard Burthogge',
                           'Joseph Butler',
                           'Samuel Butler',
                           'Pierre Jean George Cabanis',
                           'Amílcar Cabral',
                           'Edward Caird',
                           'Dorion Cairns',
                           'Thomas Cajetan',
                           'Calcidius',
                           'Mario Calderoni',
                           'Callicles',
                           'John Calvin',
                           'Tommaso Campanella',
                           'George Campbell',
                           'Norman Robert Campbell',
                           'Albert Camus',
                           'Georges Canguilhem',
                           'Georg Cantor',
                           'Johannes Capreolus',
                           'Claudia Card',
                           'Gerolamo Cardano',
                           'Thomas Carlyle',
                           'Gershom Carmichael',
                           'Rudolf Carnap',
                           'Carneades',
                           'Lewis Carroll',
                           'Nancy Cartwright',
                           'Carl Gustav Carus',
                           'Paul Carus',
                           'Antonio Caso',
                           'Ernst Cassirer',
                           'Hector-Neri Castañeda',
                           'Carlo Cattaneo',
                           'Stanley Cavell',
                           'Margaret Cavendish',
                           'Celsus of Alexandria',
                           'Michel de Certeau',
                           'Pyotr Chaadaev',
                           'Houston Stewart Chamberlain',
                           'Chanakya',
                           "Chang Hsueh-ch'eng",
                           'Chang Tsai',
                           'William Ellery Channing',
                           'Walter Charleton',
                           'Pierre Charron',
                           'François-René de Chateaubriand',
                           'Walter Chatton',
                           "Ch'en Hsien-chang",
                           'Cheng Hao',
                           'Cheng Hsuan',
                           'Cheng Yi',
                           'Nikolai Chernyshevsky',
                           'Chia Yi',
                           'Chiao Hung',
                           'Boris Chicherin',
                           "Ch'ien Mu",
                           'Chih Tun',
                           'William Chillingworth',
                           'Roderick Chisholm',
                           'Noam Chomsky',
                           'Tasan Chông Yagyong',
                           'Chou Tun-Yi',
                           'Christine de Pizan',
                           'Chrysippus',
                           'Thomas Chubb',
                           'Alonzo Church',
                           'Patricia Churchland',
                           'Paul Churchland',
                           'Leon Chwistek',
                           'Cicero',
                           'August Cieszkowski',
                           'Emil Cioran',
                           'Hélène Cixous',
                           'Clarembald of Arras',
                           'Samuel Clarke',
                           'Johannes Clauberg',
                           'Cleanthes',
                           'Clement of Alexandria',
                           'Catherine Clément',
                           'Cleomedes',
                           'William Kingdon Clifford',
                           'Catherine Trotter Cockburn',
                           'Lorraine Code',
                           'G.A. Cohen',
                           'Hermann Cohen',
                           'L. Jonathan Cohen',
                           'Morris Raphael Cohen',
                           'Samuel Taylor Coleridge',
                           'John Colet',
                           'Lucio Colletti',
                           'Arthur Collier',
                           'R. G. Collingwood',
                           'Anthony Collins',
                           'John Comenius',
                           'Auguste Comte',
                           'Étienne Bonnot de Condillac',
                           'Marquis de Condorcet',
                           'Confucius',
                           'Benjamin Constant',
                           'Lady Anne Finch Conway',
                           'Nicolaus Copernicus',
                           'Henry Corbin',
                           'Geraud de Cordemoy',
                           'Moses ben Jacob Cordovero',
                           'Uriel da Costa',
                           'Antoine Augustin Cournot',
                           'Victor Cousin',
                           'Louis Couturat',
                           'William Crathorn',
                           'Cratylus',
                           'James Edwin Creighton',
                           'Hasdai Crescas',
                           'Benedetto Croce',
                           'Christian August Crusius',
                           'Ralph Cudworth',
                           'Nathaniel Culverwel',
                           'Richard Cumberland',
                           'Cyrano de Bergerac',
                           'Heinrich Czolbe']

filosofos_wikipedia_a_c_fechas = {"Adi Shankara": 'unknown',
                                  "Nicola Abbagnano": '1901-1990',
                                  "Muhammad Abduh": '1849-1905',
                                  "Peter Abelard": '1079-1142',
                                  "Abhinavagupta": '975-1025',
                                  "Isaac ben Judah Abravanel": '1437-1508',
                                  "Judah ben Isaac Abravanel": '1460-1535',
                                  "Marilyn McCord Adams": '1943-',
                                  "Robert Adams": '1937-',
                                  "Joseph Addison": '1672-1719',
                                  "Adelard of Bath": 'unknown',
                                  "Alfred Adler": '1870-1937',
                                  "Theodor Adorno": '1903-1969',
                                  "Aenesidemus": 'unknown',
                                  "Jamal al-Din al-Afghani": '1839-1897',
                                  "Rodolphus Agricola": '1443-1485',
                                  "Agrippa the Sceptic": 'unknown',
                                  "Heinrich Cornelius Agrippa": '1436-1535',
                                  "Pierre d'Ailly": '1350-1420',
                                  "Kazimierz Ajdukiewicz": '1890-1963',
                                  "Hans Albert": '1921-',
                                  "Albert of Saxony": '1316-1390',
                                  "Albertus Magnus": '1193-1280',
                                  "Joseph Albo": '1380-1444',
                                  "Alcinous": 'unknown',
                                  "Alcmaeon of Croton": 'unknown',
                                  "Virgil Aldrich": '1903-1998',
                                  "Yohanan ben Isaac Alemanno": '1433-1504',
                                  "Alexander of Aphrodisias": 'unknown',
                                  "Alexander of Hales": '-1245',
                                  "Samuel Alexander": '1859-1938',
                                  "Dante Alighieri": '1265-1321',
                                  "Antonio Aliotta": '1881-1964',
                                  "Archibald Alison": '1757-1839',
                                  "Abd al-Jabiri": '1935-',
                                  "Abdullah al-Qasemi": '1907-1996',
                                  "William Alston": '1921-2009',
                                  "Johannes Althusius": '1557-1638',
                                  "Louis Althusser": '1918-1990',
                                  "Robert Alyngton": '-1398',
                                  "Bhimrao Ambedkar": '1891-1956',
                                  "Ambrose": '340-397',
                                  "Abu'l Hasan Muhammad Ibn Yusuf al-'Amiri": '-992',
                                  "Ammonius Hermiae": 'unknown',
                                  "Ammonius Saccas": 'unknown',
                                  "André-Marie Ampère": '1775-1836',
                                  "Anton Wilhelm Amo": '1703-1759',
                                  "Anaxagoras": 'unknown',
                                  "Anaxarchus": 'unknown',
                                  "Anaximander": '610BC-546BC',
                                  "Anaximenes of Miletus": 'unknown',
                                  "Alan Ross Anderson": '1925-1973',
                                  "John Anderson": '1893-1962',
                                  "Ando Shoeki": '1703-1762',
                                  "Andronicus of Rhodes": 'unknown',
                                  "Peter Annet": '1693-1769',
                                  "Anniceris": 'unknown',
                                  "G. E. M. Anscombe": '1918-2001',
                                  "Anselm": '1034-1109',
                                  "Antiochus of Ascalon": '130BC-68BC',
                                  "Antiphon": '480BC-403BC',
                                  "Antisthenes": '444-365',
                                  "Karl-Otto Apel": '1922-2017',
                                  "Apuleius": '123-180',
                                  "Thomas Aquinas": '1225-1274',
                                  "Isaac ben Moses Arama": '1420-1494',
                                  "Arcesilaus": '316BC-241BC',
                                  "Archytas": '428BC-347BC',
                                  "Roberto Ardigò": '1828-1920',
                                  "Hannah Arendt": '1906-1975',
                                  "Aristippus of Cyrene": '435BC-366BC',
                                  "Aristo of Chios": 'unknown',
                                  "Aristotle": '384BC-322BC',
                                  "Arius": '256-336',
                                  "Mohammed Arkoun": '1928-',
                                  "Jacobus Arminius": '1560-1609',
                                  "David Malet Armstrong": '1926-',
                                  "Antoine Arnauld": '1612-1694',
                                  "Matthew Arnold": '1822-1888',
                                  "Kenneth Arrow": '1921-2017',
                                  "Valentin Ferdinandovich Asmus": '1894-1975',
                                  "Mary Astell": '1666-1731',
                                  "Athanasius of Alexandria": '298-373',
                                  "Gwenaëlle Aubry": '1971-',
                                  "Augustine of Hippo": '354-430',
                                  "Marcus Aurelius": '121-180',
                                  "Peter Aureol": '1280-1322',
                                  "Sri Aurobindo": '1872-1950',
                                  "John Austin": '1790-1859',
                                  "John Langshaw Austin": '1911-1960',
                                  "Richard Avenarius": '1843-1896',
                                  "Averroes": '1126-1198',
                                  "Avicenna": '980-1037',
                                  "Alfred Jules Ayer": '1910-1989',
                                  "Franz Xaver von Baader": '1765-1841',
                                  "Charles Babbage": '1791-1871',
                                  "Gaston Bachelard": '1884-1962',
                                  "Johann Jakob Bachofen": '1815-1887',
                                  "Francis Bacon": '1561-1626',
                                  "Roger Bacon": '1214-1294',
                                  "Alain Badiou": '1937' ,
                                  "Hibat Allah Abu'l-Barakat al-Baghdaadi": '1080-1165',
                                  "Annette Baier": '1929',
                                  "Kurt Baier": '1917-2010',
                                  "Alexander Bain": '1818-1903',
                                  "Karl Friedrich Bahrdt": '1741-1792',
                                  "Lynne Rudder Baker": '1944-',
                                  "Mikhail Bakhtin": '1895-1975',
                                  "Mikhail Bakunin": '1814-1876',
                                  "Arthur Balfour": '1848-1930',
                                  "John Balguy": '1686-1748',
                                  "Domingo Báñez": '1528-1604',
                                  "Antonio Banfi": '1886-1957',
                                  "Abraham bar Hiyya Ha-Nasi": '1070-1136',
                                  "Jonathan Barnes": '1942-',
                                  "Brian Barry": '1936-2009',
                                  "Karl Barth": '1886-1968',
                                  "Roland Barthes": '1915-1980',
                                  "Bartolus de Saxoferrato": '1313-1357',
                                  "Johann Bernhard Basedow": '1724-1790',
                                  "Basilides": '117-138',
                                  "Georges Bataille": '1897-1962',
                                  "Charles Batteux": '1713-1780',
                                  "Jean Baudrillard": '1929-2007' ,
                                  "Bruno Bauer": '1809-1882',
                                  "David Baumgardt": '1890-1963',
                                  "Alexander Gottlieb Baumgarten": '1714-1762',
                                  "Pierre Bayle": '1647-1706',
                                  "Monroe Beardsley": '1915-1985',
                                  "James Beattie": '1735-1803',
                                  "Cesare, Marquis of Beccaria": '1738-1794',
                                  "Jakob Sigismund Beck": '1761-1840',
                                  "Vissarion Belinsky": '1811-1848',
                                  "Robert Bellarmine": '1542-1621',
                                  "Nuel Belnap": '1930-',
                                  "Gustave Belot": '1859-1929',
                                  "Friedrich Eduard Beneke": '1798-1854',
                                  "Walter Benjamin": '1892-1940',
                                  "Gottfried Benn": '1886-1956',
                                  "Jonathan Bennett": '1930-',
                                  "Jeremy Bentham": '1748-1832',
                                  "Richard Bentley": '1662-1742',
                                  "Nikolai Berdyaev": '1874-1948',
                                  "Gustav Bergmann": '1906-1987',
                                  "Henri Bergson": '1859-1941',
                                  "George Berkeley": '1685-1753',
                                  "Isaiah Berlin": '1909-1997',
                                  "Claude Bernard": '1813-1878',
                                  "Bernard of Chartres": '-1130',
                                  "Bernard of Clairvaux": '1090-1153',
                                  "Bernard Silvestris": '1147-1178',
                                  "François Bernier": '1620-1688',
                                  "Eduard Bernstein": '1850-1932',
                                  "Ludwig von Bertalanffy": '1901-1972',
                                  "Bhartrhari": 'unknown',
                                  "Gabriel Biel": '1425-1495',
                                  "Georg Bernhard Bilfinger": '1693-1750',
                                  "Alfred Binet": '1857-1911',
                                  "Ludwig Binswanger": '1881-1966',
                                  "Max Black": '1909-1988',
                                  "Simon Blackburn": '1944',
                                  "William Blackstone": '1723-1780',
                                  "Hugh Blair": '1718-1800',
                                  "William Blake": '1757-1827',
                                  "Maurice Blanchot": '1907-2003',
                                  "Brand Blanshard": '1892-1987',
                                  "Blasius of Parma": '1345-1416',
                                  "Ernst Bloch": '1885-1977',
                                  "Ned Block": '1942-',
                                  "Maurice Blondel": '1861-1949',
                                  "Charles Blount": '1654-1693',
                                  "Norberto Bobbio": '1909-2004',
                                  "Jean Bodin": '1530-1596',
                                  "Anicius Manlius Severinus Boethius": '480-524',
                                  "Boetius of Dacia": '1240-1280',
                                  "Alexander Bogdanov": '1873-1928',
                                  "Jakob Böhme": '1575-1624',
                                  "David Bohm": '1917-1992',
                                  "Niels Bohr": '1885-1962',
                                  "Nicolas Boileau-Despréaux": '1636-1711',
                                  "Samuel Bold": '1649-1737',
                                  "Henry St John, 1st Viscount Bolingbroke": '1678-1751',
                                  "Ludwig Boltzmann": '1844-1906',
                                  "Bernard Bolzano": '1781-1848',
                                  "Louis Gabriel Ambroise de Bonald": '1754-1840',
                                  "Francesco Bonatelli": '1830-1911',
                                  "Bonaventure": '1221-1274',
                                  "Dietrich Bonhoeffer": '1906-1945',
                                  "Charles Bonnet": '1720-1793',
                                  "George Boole": '1815-1864',
                                  "Bernard Bosanquet": '1848-1923',
                                  "Rudjer Boscovich": '1711-1787',
                                  "Pierre Bourdieu": '1930-2002',
                                  "Jacques-Bénigne Bossuet": '1627-1704',
                                  "Christopher Jacob Boström": '1797-1866',
                                  "Henri de Boulainvilliers": '1658-1722',
                                  "Emile Boutroux": '1845-1921',
                                  "Oets Kolk Bouwsma": '1898-1978',
                                  "Borden Parker Bowne": '1847-1910',
                                  "Robert Boyle": '1627-1691',
                                  "F. H. Bradley": '1846-1924',
                                  "Thomas Bradwardine": '1290-1349',
                                  "Richard-Bevan Braithwaite": '1900-1990',
                                  "Richard B. Brandt": '1910-1997',
                                  "Franz Brentano": '1838-1917',
                                  "Percy Williams Bridgman": '1882-1961',
                                  "Edgar S. Brightman": '1884-1953',
                                  "Jean Anthelme Brillat-Savarin": '1755-1826',
                                  "Richard Brinkley": '1350-1373',
                                  "Radulphus Brito": '1270-1320',
                                  "C. D. Broad": '1887-1971',
                                  "Thom Brooks": '1973-',
                                  "Luitzen Egbertus Jan Brouwer": '1881-1966',
                                  "Thomas Brown": '1778-1820',
                                  "Peter Browne": '1666-1735',
                                  "Orestes Brownson": '1803-1876',
                                  "Emil Brunner": '1889-1966',
                                  "Giordano Bruno": '1548-1600',
                                  "Leon Brunschvicg": '1869-1944',
                                  "James Bryce, 1st Viscount Bryce": '1838-1922',
                                  "Martin Buber": '1878-1965',
                                  "Justus Buchler": '1914-1991',
                                  "Ludwig Büchner": '1824-1899',
                                  "Henry Thomas Buckle": '1821-1862',
                                  "Malcolm Budd": '1941-',
                                  "Johann Franz Buddeus": '1667-1729',
                                  "Buddhaghosa": 'unknown',
                                  "Claude Buffier": '1661-1737',
                                  "Georges-Louis Leclerc, Comte de Buffon": '1707-1788',
                                  "Sergei Nikolaevich Bulgakov": '1871-1944',
                                  "Edward Bullough": '1880-1934',
                                  "Rudolf Bultmann": '1884-1976',
                                  "Jacob Burckhardt": '1818-1897',
                                  "Tyler Burge": '1946-',
                                  "Jean Buridan": '1300-1358',
                                  "Edmund Burke": '1729-1797',
                                  "Walter Burley": '1275-1345',
                                  "Myles Frederic Burnyeat": '1939-',
                                  "Richard Burthogge": '1638-1704',
                                  "Joseph Butler": '1692-1752',
                                  "Samuel Butler": '1835-1902',
                                  "Pierre Jean George Cabanis": '1757-1808',
                                  "Amílcar Cabral": '1924-1973',
                                  "Edward Caird": '1835-1908',
                                  "Dorion Cairns": '1901-1973',
                                  "Thomas Cajetan": '1469-1534',
                                  "Calcidius": 'unknown',
                                  "Mario Calderoni": '1879-1914',
                                  "Callicles": 'unknown',
                                  "John Calvin": '1509-1564',
                                  "Tommaso Campanella": '1568-1639',
                                  "George Campbell": '1719-1796',
                                  "Norman Robert Campbell": '1880-1949',
                                  "Albert Camus": '1913-1960',
                                  "Georges Canguilhem": '1904-1995',
                                  "Georg Cantor": '1845-1918',
                                  "Johannes Capreolus": '1380-1444',
                                  "Claudia Card": '1940-',
                                  "Gerolamo Cardano": '1501-1576',
                                  "Thomas Carlyle": '1795-1881',
                                  "Gershom Carmichael": '1672-1729',
                                  "Rudolf Carnap": '1891-1970',
                                  "Carneades": '214BC-129BC',
                                  "Lewis Carroll": '1832-1898',
                                  "Nancy Cartwright": '1943-',
                                  "Carl Gustav Carus": '1789-1869',
                                  "Paul Carus": '1852-1919',
                                  "Antonio Caso": '1883-1946',
                                  "Ernst Cassirer": '1874-1945',
                                  "Hector-Neri Castañeda": '1924-1991',
                                  "Carlo Cattaneo": '1801-1869',
                                  "Stanley Cavell": '1926-',
                                  "Margaret Cavendish": '1623-1673',
                                  "Celsus of Alexandria": 'unknown',
                                  "Michel de Certeau": '1925-1986',
                                  "Pyotr Chaadaev": '1794-1856',
                                  "Houston Stewart Chamberlain": '1855-1927',
                                  "Chanakya": '321BC-296BC',
                                  "Chang Hsueh-ch'eng": '1738-1801',
                                  "Chang Tsai": '1020-1077',
                                  "William Ellery Channing": '1780-1842',
                                  "Walter Charleton": '1619-1707',
                                  "Pierre Charron": '1541-1603',
                                  "François-René de Chateaubriand": '1768-1848',
                                  "Walter Chatton": '1290-1343',
                                  "Ch'en Hsien-chang": '1428-1500',
                                  "Cheng Hao": '1032-1085',
                                  "Cheng Hsuan": '127-200',
                                  "Cheng Yi": '1033-1107',
                                  "Nikolai Chernyshevsky": '1828-1889',
                                  "Chia Yi": '201BC-169BC',
                                  "Chiao Hung": '1540-1620',
                                  "Boris Chicherin": '1828-1904',
                                  "Ch'ien Mu": '1895-1990',
                                  "Chih Tun": '314-366',
                                  "William Chillingworth": '1602-1644',
                                  "Roderick Chisholm": '1916-1999',
                                  "Noam Chomsky": '1928-',
                                  "Tasan Chông Yagyong": '1762-1836',
                                  "Chou Tun-Yi": '1017-1073',
                                  "Christine de Pizan": '1365-1430',
                                  "Chrysippus": '279BC-207BC',
                                  "Thomas Chubb": '1679-1747',
                                  "Alonzo Church": '1903-1995',
                                  "Patricia Churchland": '1943-',
                                  "Paul Churchland": '1942-',
                                  "Leon Chwistek": '1884-1944',
                                  "Cicero": '106BC-43BC',
                                  "August Cieszkowski": '1814-1894',
                                  "Emil Cioran": '1911-1995',
                                  "Hélène Cixous": '1937-',
                                  "Clarembald of Arras": '1110-1187',
                                  "Samuel Clarke": '1675-1729',
                                  "Johannes Clauberg": '1622-1665',
                                  "Cleanthes": '301BC-232BC',
                                  "Clement of Alexandria": 'unknown',
                                  "Catherine Clément": '1939-',
                                  "Cleomedes": 'unknown',
                                  "William Kingdon Clifford": '1845-1879',
                                  "Catherine Trotter Cockburn": '1679-1749',
                                  "Lorraine Code": '1937-',
                                  "G.A. Cohen": '1941-2009',
                                  "Hermann Cohen": '1842-1918',
                                  "L. Jonathan Cohen": '1923-',
                                  "Morris Raphael Cohen": '1880-1947',
                                  "Samuel Taylor Coleridge": '1772-1834',
                                  "John Colet": '1466-1519',
                                  "Lucio Colletti": '1924-2001',
                                  "Arthur Collier": '1680-1732',
                                  "R. G. Collingwood": '1889-1943',
                                  "Anthony Collins": '1676-1729',
                                  "John Comenius": '1592-1670',
                                  "Auguste Comte": '1798-1857',
                                  "Étienne Bonnot de Condillac": '1715-1780',
                                  "Marquis de Condorcet": '1743-1794',
                                  "Confucius": '551BC-479BC',
                                  "Benjamin Constant": '1767-1830',
                                  "Lady Anne Finch Conway": '1631-1679',
                                  "Nicolaus Copernicus": '1473-1543',
                                  "Henry Corbin": '1903-1978',
                                  "Geraud de Cordemoy": '1626-1684',
                                  "Moses ben Jacob Cordovero": '1522-1570',
                                  "Uriel da Costa": '1585-1640',
                                  "Antoine Augustin Cournot": '1801-1877',
                                  "Victor Cousin": '1792-1867',
                                  "Louis Couturat": '1868-1914',
                                  "William Crathorn": 'unknown',
                                  "Cratylus": 'unknown',
                                  "James Edwin Creighton": '1861-1924',
                                  "Hasdai Crescas": '1340-1410',
                                  "Benedetto Croce": '1866-1952',
                                  "Christian August Crusius": '1715-1775',
                                  "Ralph Cudworth": '1617-1688',
                                  "Nathaniel Culverwel": '1619-1651',
                                  "Richard Cumberland": '1631-1718',
                                  "Cyrano de Bergerac": '1619-1655',
                                  "Heinrich Czolbe": '1819-1873'}